"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Sequence, Union
from albumentations.augmentations.utils import clipped, preserve_shape

__all__ = ["blur", "median_blur", "gaussian_blur", "glass_blur"]
@preserve_shape
def blur(img: np.ndarray, ksize: int) -> np.ndarray:
    ...

@preserve_shape
def median_blur(img: np.ndarray, ksize: int) -> np.ndarray:
    ...

@preserve_shape
def gaussian_blur(img: np.ndarray, ksize: int, sigma: float = ...) -> np.ndarray:
    ...

@preserve_shape
def glass_blur(img: np.ndarray, sigma: float, max_delta: int, iterations: int, dxy: np.ndarray, mode: str) -> np.ndarray:
    ...

def defocus(img: np.ndarray, radius: int, alias_blur: float) -> np.ndarray:
    ...

def central_zoom(img: np.ndarray, zoom_factor: int) -> np.ndarray:
    ...

@clipped
def zoom_blur(img: np.ndarray, zoom_factors: Union[np.ndarray, Sequence[int]]) -> np.ndarray:
    ...

